### PR TITLE
Added scenario .tms files to lobby export.  Also changed export-scena…

### PR DESCRIPTION
**Pull request by landersk61**
…rios to use const/let convention

### CODE REVIEW

**Comment by longtinm** [comment]
What happens if a map isn't available?  Does the user get notified?

**Comment by landersk61** [comment]
Good question @longtinm.  I don't think it does.  My addition was intended to match how we grab the .tif file (which does not notify the user if a .tif is not there).  It just adds the file to the export if it matches in name.  Since we allow users to upload just the simple image as a map, I didn't think we required a notification to the user if the .tms is missing.  If we think it should be required (or if it would benefit the user) to be notified that there is no .tms, I can take a look at doing that.  But I could also see a user seeing a message about a missing .tms map as being confusing for users that aren't as familiar with the inner workings of ITDG as we are.

**Review by longtinm — APPROVED** [review]

**Comment by eric79** [comment]
I don't know if this is related to your change, but when I tried to export one of my tile set scenarios, I got the following error on the server:

image

**Comment by landersk61** [comment]
@eric79 , Hmmm...It's probably a separate issue.  What media is associated with the scenario? (i.e. which map, any images, multimedia, playback, etc?)  It sounds like it's trying to add the same file twice.  My suspicion is that you have two of the same file referenced in the scenario somewhere and we need to be smart enough to only add it once in the export.

**Comment by eric79** [comment]
Ah ... this is a scenario that was saved in the version of ITDG that stored the `.tms` map url in the state.  As a result, the list of input file paths I got was:

image

I think that what you suggested would fix it.  We could ensure that there are no repeats in `inputFilePaths`.

**Comment by landersk61** [comment]
Thanks @eric79 ! Sounds good.  I'll make the change.

**Comment by eric79** [comment]
That's definitely better.  The issue now is that for an old scenario like the one that I have, the `.jpg` file is not included in the export, which the app now expects to be there.

When Mike is able to embed the `.jpg` and `.tif` files in the `.tms.zip` file, I think the right answer would be to just export the `.tms.zip` file.

For now, though, maybe the best thing would be to extract the base map name and try to export `.jpg`, `.png`, `.gif`, `.tif`, or `.tms` file?

**Review by eric79 — CHANGES_REQUESTED** [review]
That's definitely better. The issue now is that for an old scenario like the one that I have, the `.jpg` file is not included in the export, which the app now expects to be there.

When Mike is able to embed the `.jpg` and `.tif` files in the `.tms.zip` file, I think the right answer would be to just export the `.tms.zip` file.

For now, though, maybe the best thing would be to extract the base map name and try to export `.jpg`, `.png`, `.gif`, `.tif`, or `.tms` file?

**Review by eric79 — APPROVED** [review]
Works like a charm now!  :smile:

**Pull request merged**
