### PR TITLE
Fix cache misses with generate overlay requests

### PR DESCRIPTION
**Pull request by robertdhernandez**

### CODE REVIEW

**Comment by longtinm** [comment]
Thanks!  Did you verify this also works with SandTable requests?

**Comment by robertdhernandez** [comment]
I have only verified with ITDG.

**Comment by longtinm** [comment]
Ok, please test it with the SandTable app and let me know the results.  Thanks.

**Comment by robertdhernandez** [comment]
It works in SandTable, but with an asterisk. 

ITDG sends positions in integer image positions where as SandTable sends positions in floating-point, Unity coordinates. If you make an overlay request, clear it, then repeat the request without touching anything, it will use the cached version; otherwise, it will treat it as a new request and re-generate it. Due to SandTable's heavy use of floating-point numbers in positioning and EM parameters, it is not likely to use trigger the cached version.

I believe this would have been an issue with the previous system for exactly the same reason.

**Review by longtinm — APPROVED** [review]

**Pull request merged**
