### PR TITLE
konva: Allow nodes to turn off scale and rotation to improve draw performance

### PR DESCRIPTION
**Pull request by eric79**
@landersk61 @youngca @davideaster @AmbientOSX, would you mind reviewing?

### CODE REVIEW

**Comment by landersk61** [comment]
:+1:

**Comment by eric79** [comment]
Thanks, @landersk61 !  By the way, I should mention that this change cut the render time in the `batchDraw` in half.  Pretty slick.  Thanks for showing me that optimization page that suggested it, @landersk61 .  :smile:

**Comment by youngca** [comment]
:-1: 

Nice, easy fix to get a lot of bang for the buck.  @landersk61, thanks for identifying that and @eric79, thanks for trying it.

However, it turns out that we're using rotation to set the angle of our arrow drawings.  When I'm creating the drawing in the view, I can stretch it out and rotate it to the correct angle, however, as soon as I release the mouse button so the object can be created in the model, the arrow snaps to its default pointing along the positive x-axis.
Therefore, we either need to (a) make special exceptions or (b) let the view compute the positions of the points based on the rotation transform and then set the rotated point locations explicitly when creating in the model.

**Comment by eric79** [comment]
@youngca this is ready for re-review.  It no longer breaks arrows and thick arrows.  :smile:

**Comment by eric79** [comment]
@youngca After your verbal "looks okay", I'm going to go ahead and merge this.  Testing has gone fine on my end.  With this back on the `tdg` branch, @landersk61 and I will be free to do performance testing.

**Pull request merged**
