### PR TITLE
Trim string inputs and normalize number inputs

### PR DESCRIPTION
**Pull request by davideaster**
@youngca @eric79

### CODE REVIEW

**Comment by eric79** [comment]
One thing I noticed is that it appears that the sorting of scenarios by name happens before the `trim` such that anything that has a leading space sorts to the top, which is undesirable.

It's up to you whether you want to fix that on this PR or consider that future work, since you fixed the much more important bug already.

:+1:

**Comment by davideaster** [comment]
Good point. The sort on `name` is actually sorting by the slug. An improved lobby view should switch to the `title` display field and trim appropriately.

Updated the slug generator to also trim whitespace so that the slugs sort better.

**Comment by eric79** [comment]
It works!  You have made a good thing even better.  :smile: :+1:

**Comment by eric79** [comment]
Interesting ... did you merge `tdg` back to this branch rather than rebasing this branch on top of `tdg`?

**Comment by davideaster** [comment]
I merged from the PR. There was a small conflict and I resolved it using GitHub's UI to see what would happen. Next time, I would rebase and resolve locally to keep the history cleaner.

**Comment by eric79** [comment]
Gotcha.  Well, thanks for doing the experiment so I don't have to!  :smile:

**Pull request merged**
